name: Northwestern Plastic Surgery
favicon: null
layout_spectrum: 0.22570092510432005
typography_spectrum: 0.21277299872599542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9827319402247667
  lightness: 0.43071456789039075
  saturation: 0.63489776593633
  rhythmicContrast: 0.4229474808089435
purpose: []
